Frontend build and Unit tests
cormac-larkin-kainos/Floor_Is_Java_Frontend pull request #2
Opened 2023-11-08 15:23 UTC by JonnyEvans99

2023-11-08 15:47 UTC, cormac-larkin-kainos approved these changes

2023-11-08 16:04 UTC, shaunganley requested changes

2023-11-08 16:04 UTC, shaunganley commented on controller/JobController.ts
> +        console.log("Hello")
remove these logs

2023-11-08 16:04 UTC, shaunganley commented on model/Job.ts
> +    job_title?: string
don't think these need to be optional

2023-11-08 16:04 UTC, shaunganley commented on service/JobService.ts
> +    URL: string = "http://localhost:8080/api/jobs";
don't hardcode http://localhost:8080/api, set it as an env var and pull it in

2023-11-08 16:04 UTC, shaunganley commented on service/JobService.ts
> +            console.log("Jobs -> ", jobs);
remove logs

2023-11-08 16:05 UTC, shaunganley commented
also, update the readme to run tests

2023-11-09 09:53 UTC, shaunganley approved these changes

2023-11-09 09:55 UTC, merged